name = "lapce-deno"
version = "0.0.0"
author = "panekj"
display-name = "Deno"
description = "Deno"
wasm = "bin/lapce-deno.wasm"

[activation]
language = [
  "javascript",
  "javascriptreact",
  "jsx",
  "typescript",
  "typescriptreact",
  "tsx",
  "markdown",
  "json",
  "jsonc",
]
# workspace-contains = []

# [config."volt.serverArgs"]
# default = ["lsp"]
